restore_zone_states:
  name: "Restore Zone States"
  description: "Restore saved states for a zone"
  fields:
    zone_id:
      name: "Zone ID"
      description: "The zone ID to restore"
      required: true
      selector:
        text: